[package]
name = "tezos_context"
version = "0.9.1"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
# this package should not have any internal dependencies