[package]
name = "tezos_context"
version = "1.4.0"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.8"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
ocaml-interop = { version = "0.8.0", features = ["without-ocamlopt"] }
# this package should not have any internal dependencies except this one
tezos-sys = { path = "../sys" }
