[package]
name = "tezos_context"
version = "1.9.0"
authors = ["Branislav Kontur <branislav.kontur@viablesystems.io>"]
edition = "2018"

[dependencies]
blake2 = "0.9"
crossbeam-channel = "0.5"
anyhow = "1.0"
thiserror = "1.0"
hex = "0.4"
lazy_static = "1.4"
leb128 = "0.2"
modular-bitfield = "0.11"
ocaml-interop = { version = "0.8.4", features = ["without-ocamlopt", "caml-state"] }
serde = { version = "1.0", features = ["derive", "rc"] }
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
static_assertions = "1.1"
strum = "0.20"
strum_macros = "0.20"
# Internal dependencies
ipc = { path = "../../ipc" }
tezos-sys = { path = "../sys" }
tezos_api = { path = "../api" }
tezos_spsc = { path = "../spsc" }
crypto = { path = "../../crypto" }
tezos_timing = { path = "../timing" }
rand = "0.8"

[dev-dependencies]
flate2 = "1.0"
serde_json = "1.0"
storage = { path = "../../storage" }
tezos_messages = { path = "../messages" }
