[package]
name = "tezos_context_api"
version = "1.13.0"
edition = "2018"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
nom = "6.1"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }
