[package]
name = "tezos_context_api"
version = "2.4.0"
edition = "2021"
rust-version = "1.58"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9"
time = { version = "0.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
nom = "6.1"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }
fuzzcheck = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }

[features]
fuzzing = ["fuzzcheck", "crypto/fuzzing", "tezos_encoding/fuzzing", "tezos_messages/fuzzing"]

