[package]
name = "tezos_interop"
version = "1.10.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
futures = { version = "0.3", features = ["thread-pool"] }
hex = "0.4"
lazy_static = "1.4"
ocaml-interop = { version = "0.8.7", features = ["without-ocamlopt", "caml-state"] }
serde_json = "1.0"
# local dependencies
tezos-sys = { path = "../sys" }
tezos_api = { path = "../api" }
tezos_conv = { path = "../conv" }
tezos_messages = { path = "../messages" }
tezos_context = { path = "../context" }
tezos_context_api = { path = "../context-api" }
crypto = { path = "../../crypto" }

[dev-dependencies]
crypto = { path = "../../crypto" }
serial_test = "0.5"
criterion = "0.3"

[[bench]]
name = "interop_benchmark"
harness = false
