[package]
name = "tezos_interop"
version = "0.2.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
futures-preview = "0.3.0-alpha.19"
lazy_static = "1.4.0"
log = "0.4.8"
ocaml = "0.7.0"

[build-dependencies]
colored = "1.8.0"
fs_extra = "1.1.0"
hex-literal = "0.2.1"
os_type = "2.2.0"
sha2 = "0.8.0"