[package]
name = "tezos_interop"
version = "1.4.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = { version = "0.3", features = ["thread-pool"] }
hex = "0.4"
lazy_static = "1.4"
ocaml-interop = { version = "0.8.1" }
serde_json = "1.0"
# local dependencies
tezos-sys = { path = "../sys" }
tezos_api = { path = "../api" }
tezos_interop_callback = { path = "../interop_callback" }
tezos_messages = { path = "../messages" }
tezos_new_context = { path = "../new_context" }
crypto = { path = "../../crypto" }

[dev-dependencies]
crypto = { path = "../../crypto" }
tezos_context = { path = "../context" }
serial_test = "0.5"
criterion = "0.3"

[[bench]]
name = "interop_benchmark"
harness = false
