[package]
name = "tezos_interop"
version = "0.10.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = { version = "0.3", features = ["thread-pool"] }
hex = "0.4"
lazy_static = "1.4"
ocaml-interop = { version = "0.5.0", features = ["without-ocamlopt"] }
serde_json = "1.0"
# local dependencies
tezos_api = { path = "../api" }
tezos_interop_callback = { path = "../interop_callback" }
tezos_messages = { path = "../messages" }

[build-dependencies]
colored = "2.0"
fs_extra = "1.1"
hex = "0.4"
os_type = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"

[dev-dependencies]
crypto = { path = "../../crypto" }
tezos_context = { path = "../context" }
serial_test = "0.5"
criterion = "0.3"

[[bench]]
name = "interop_benchmark"
harness = false