[package]
name = "shell"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
dns-lookup = "1.0.1"
failure = "0.1"
futures = "0.3"
getset = "0.0.9"
hex = "0.4"
itertools = "0.8.0"
lazy_static = "1.4.0"
nix = "0.15.0"
page_size = "0.4.1"
rand = "0.7.3"
regex = "1.3.1"
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
rocksdb = "0.13"
slog = "2.5"
serde = "1.0.102"
serde_json = "1.0"
tokio = { version = "0.2", features = ["time", "tcp", "rt-core"] }
# local dependencies
crypto = { path = "../crypto" }
networking = { path = "../networking" }
storage = { path = "../storage" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }
tezos_wrapper = { path = "../tezos/wrapper" }

[dev-dependencies]
jsonpath = "0.1.1"
slog-async = "2.3"
slog-term = "2.4"
tezos_client = { path = "../tezos/client" }
zip = "0.5.5"