[package]
name = "shell"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
dns-lookup = "1.0.1"
failure = "0.1"
futures-preview = "0.3.0-alpha.19"
hex = "0.4"
itertools = "0.8.0"
lazy_static = "1.4.0"
nix = "0.15.0"
page_size = "0.4.1"
rand = "0.7.2"
regex = "1.3.1"
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
rocksdb = "0.12"
slog = "2.5"
serde = "1.0.102"
serde_json = "1.0"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
tokio-timer = "0.2.0-alpha.6"
# local dependencies
networking = { path = "../networking" }
storage = { path = "../storage" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }
tezos_wrapper = { path = "../tezos/wrapper" }
