[package]
name = "tenderbake"
version = "2.3.3"
edition = "2021"

[dependencies]
libm = { version = "0.2.2" }
serde = { version = "1.0", features = ["derive"] }
crypto = { path = "../../crypto" }

fuzzcheck = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }
fuzzcheck_mutators_derive = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }

[features]
fuzzing = [
    "fuzzcheck",
    "fuzzcheck_mutators_derive",
    "crypto/fuzzing",
]
