[package]
name = "tezos_encoding_derive"
version = "2.3.5"
authors = ["Alexander Koptelov <alexandre.koptelov@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"]}
quote = "1.0"
lazy_static = "1.4.0"
parse-display = "0.4.1"
once_cell = "1.9.0"

[features]
fuzzing = []