language: rust
rust:
  - nightly-2019-12-05

os:
  - linux

dist: xenial

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4

branches:
  only:
    - master