cargo-features = ["named-profiles"]

[workspace]
members = [
    "tla_sm",
    "tezedge_state",
    "simulator",
    "ipc",
    "logging",
    "crypto",
    "tezos/sys",
    "tezos/api",
    "tezos/messages",
    "tezos/identity",
    "tezos/interop",
    "tezos/encoding",
    "tezos/encoding-derive",
    "tezos/client",
    "tezos/wrapper",
    "tezos/context",
    "tezos/spsc",
    "tezos/timing",
    "tezos/lib_storage_ffi",
    "networking",
    "shell",
    "storage",
    "sandbox",
    "light_node",
    "new_node",
    "monitoring",
    "protocol_runner",
    "rpc",
    "fuzz/ack_message",
    "fuzz/advertise_message",
    "fuzz/block_header_message",
    "fuzz/current_branch_message",
    "fuzz/current_head_message",
    "fuzz/connection_message",
    "fuzz/metadata_message",
    "fuzz/operation_message",
    "fuzz/operations_for_blocks_message",
    "fuzz/peer_response_message",
    "fuzz/protocol_message",
]

[patch.crates-io]
ocaml-boxroot-sys = { git = "https://gitlab.com/bruno.deferrari/ocaml-boxroot.git", branch = "ocaml-410-headers" }
librocksdb-sys = { git = "https://github.com/tezedge/rust-rocksdb.git", tag = "tezedge-v0.17.0-1" }


[profile.fuzz]
inherits = "release"
opt-level = 3
debug = 2
debug-assertions = true  # TODO: test and disable if too slow
overflow-checks = true
lto = true
panic = "abort"
incremental = false
codegen-units = 1
