cargo-features = ["named-profiles"]

[workspace]
members = [
    "ipc",
    "async-ipc",
    "logging",
    "crypto",
    "tezos/sys",
    "tezos/api",
    "tezos/conv",
    "tezos/messages",
    "tezos/identity",
    "tezos/interop",
    "tezos/encoding",
    "tezos/encoding-derive",
    "tezos/context",
    "tezos/context-api",
    "tezos/context-ipc-client",
    "tezos/context-tool",
    "tezos/protocol-ipc-client",
    "tezos/protocol-ipc-messages",
    "tezos/spsc",
    "tezos/timing",
    "tezos/lib_storage_ffi",
    "networking",
    "shell",
    "shell-integration",
    "shell_automaton",
    "shell_automaton/testing",
    "storage",
    "sandbox",
    "light_node",
    "monitoring",
    "protocol_runner",
    "rpc",
    "edgekv",
    "edgekv/db-checker",
    "fuzz/ack_message",
    "fuzz/advertise_message",
    "fuzz/block_header_message",
    "fuzz/current_branch_message",
    "fuzz/current_head_message",
    "fuzz/connection_message",
    "fuzz/metadata_message",
    "fuzz/operation_message",
    "fuzz/operations_for_blocks_message",
    "fuzz/peer_response_message",
    "fuzz/protocol_message",
]

[patch.crates-io]
ocaml-boxroot-sys = { git = "https://gitlab.com/bruno.deferrari/ocaml-boxroot.git", branch = "ocaml-410-headers" }
librocksdb-sys = { git = "https://github.com/tezedge/rust-rocksdb.git", tag = "tezedge-v0.17.0-1" }

[profile.fuzz]
inherits = "release"
opt-level = 3
debug = 2
debug-assertions = true  # TODO: test and disable if too slow
overflow-checks = true
lto = true
panic = "abort"
incremental = false
codegen-units = 1
