version: "3"

services:

  tezedge-debugger:
    image: tezedge/tezedge-debugger:v1.6.9
    privileged: true
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "tezedge-debug-data:/tmp/volume/tezedge:ro"
      - "./docker/debug.debugger-config.toml:/home/appuser/config.toml:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/tmp/report:/tmp/report:rw"
      - "debugger-debug-data:/tmp/debugger_database"
    ports:
      - "17732:17732"      # debugger RPC port
      - "10001:10001/udp"  # debugger syslog port for tezedge node

  tezedge-node:
    image: tezedge/tezedge:v1.19.0
    pid: host
    network_mode: host
    command: ["--network", "${TEZOS_NETWORK-mainnet}", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--log", "terminal", "file", "--log-file", "/tmp/tezedge/tezedge.log", "--peer-thresh-low", "30", "--peer-thresh-high", "45", "--tezos-context-storage=${TEZOS_CONTEXT_STORAGE:-irmin}", "--context-stats-db-path", "context-stats-db", "--record-shell-automaton-state-snapshots", "--record-shell-automaton-actions"]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "tezedge-debug-data:/tmp/tezedge"
    environment:
      - TEZOS_CONTEXT=index-log-size=2_500_000

  explorer:
    image: tezedge/tezedge-explorer:v1.17.0
    environment:
      # need a better way to provide such information
      - API=[{"id":"${NODE_HOSTNAME_OR_IP:-localhost}","name":"tezedge","http":"http://${NODE_HOSTNAME_OR_IP:-localhost}:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://${NODE_HOSTNAME_OR_IP:-localhost}:4927"},{"name":"debugger","url":"http://${NODE_HOSTNAME_OR_IP:-localhost}:17732"},{"name":"monitoring"},{"name":"resources/storage"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP:-localhost}:4444/resources/tezedge"},{"name":"mempool"},{"name":"storage"},{"name":"network"},{"name":"logs"},{"name":"state"}]}]
    ports:
      - "80:80"
      - "8080:80"
    logging:
      driver: none

  monitoring:
    privileged: true
    network_mode: host
    image: tezedge/node-monitoring:v1.19.0
    pid: "host"
    command: ["--tezedge-nodes", "tezedge:18732:/tmp/tezedge", "--wait-for-nodes", "--debugger-path", "/tmp/debugger", "--rpc-port", "4444"]
    volumes:
      - "tezedge-debug-data:/tmp/tezedge"
      - "debugger-debug-data:/tmp/debugger"

volumes:
  tezedge-debug-data:
    external: false
  debugger-debug-data:
    external: false
