[package]
name = "tezos-sys"
version = "1.7.0"
authors = ["Bruno Deferrari <bruno.deferrari@simplestaking.com>"]
edition = "2018"
links = "tezos"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# NOTE: should not have any local dependencies other than the tezos-rust-libs listed here
# This crate is for linking the tezos code.
rustc-bls12-381 = { path = "../tezos-rust-libs/rustc-bls12-381" }
librustzcash = { path = "../tezos-rust-libs/librustzcash" }

[build-dependencies]
colored = "2.0"
fs_extra = "1.1"
hex = "0.4"
os_type = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
