[package]
name = "rpc"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
getset = "0.0.9"
failure = "0.1"
futures = "0.3"
hex = "0.4"
hyper = "0.13"
lazy_static = "1.4"
path-tree = "0.1.9"
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
rocksdb = "0.13"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["nested-values"] }
slog_derive = "0.1.1"
tokio = { version = "0.2", features = ["macros"] }
# local dependencies
crypto = { path = "../crypto" }
networking = { path = "../networking" }
shell = { path = "../shell" }
storage = { path = "../storage" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }

[dev-dependencies]
assert-json-diff = "1.0.0"
bytes = "0.5"