[package]
name = "logging"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"


[dependencies]
chrono = "0.4.9"
libflate = "0.1.27"
nix = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
slog-json = "2.3"

[dev-dependencies]
tempfile = "3.1.0"