[package]
name = "tezos_api"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.9"
enum-iterator = "0.5.0"
failure = "0.1"
chrono = { version = "0.4.9", features = ["serde"] }
lazy_static = "1.4"
ocaml = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.5"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
hex = "0.4"