[package]
name = "tezos_api"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
enum-iterator = "0.5.0"
failure = "0.1.5"
lazy_static = "1.4"
# TODO: change when ocaml = "0.9.0" because of Array1::from
ocaml = { git = "https://github.com/simplestaking/ocaml-rs.git", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
# local dependencies
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }