[package]
name = "tezos_api"
version = "0.7.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.9"
enum-iterator = "0.6"
failure = "0.1"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
ocaml-interop = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
# local dependencies
crypto = { path = "../../crypto" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
hex = "0.4"