[package]
name = "tezos_api"
version = "1.4.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.9"
failure = "0.1"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
ocaml-interop = { version = "0.8.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
strum = "0.20"
strum_macros = "0.20"
# local dependencies
crypto = { path = "../../crypto" }
tezos-sys = { path = "../sys" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
assert-json-diff = "1.1"
hex = "0.4"
