[package]
name = "tezos_api"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
enum-iterator = "0.5.0"
failure = "0.1"
lazy_static = "1.4"
ocaml = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }