[package]
name = "monitoring"
version = "0.9.1"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

[dependencies]
erased-serde = "0.3"
riker = "0.4"
ws = "*"
serde = "1.0"
serde_json = "1.0"
slog = { version = "2.5", features = ["nested-values"] }
slog_derive = "0.1.1"
# local dependencies
crypto = { path = "../crypto" }
networking = { path = "../networking" }
shell = { path = "../shell" }
tezos_messages = { path = "../tezos/messages" }

[dev-dependencies]
rand = "0.7.3"