version: "3"

services:

  tezedge-node:
    image: tezedge/tezedge:v1.9.1
    command: [
        "--network=granadanet",
        "--p2p-port=12534",
        "--rpc-port=12535",
        "--websocket-address=0.0.0.0:12536",
        "--peer-thresh-low", "30", "--peer-thresh-high", "45",
        "--log", "terminal", "file", "--log-file", "/context-data/tezedge.log",
        "--identity-file=/data/data/identity.json",
        "--bootstrap-db-path=/data/data/tezedge-data",
        "--tezos-data-dir=/data/data/node/data",
    ]
    hostname: tezedge-node
    volumes:
      - "data-dir-010-PtGRANAD:/data:rw"
    ports:
      - "12534:12534"
      - "12535:12535"
      - "12536:12536"
    networks:
      - default

  tezedge-explorer:
    image: tezedge/tezedge-explorer:v1.7.1
    depends_on:
      - tezedge-node
    hostname: tezedge-explorer
    environment:
      API: '[{"id":"baker.node","name":"baker.node","http":"http://${NODE_HOST}:12535", "monitoring":"", "debugger":"", "ws":"ws://${NODE_HOST}:12536", "features":["MONITORING","MEMPOOL_ACTION","STORAGE_BLOCK"]}]'
    ports:
      - "12537:80"
    networks:
      - default

volumes:
  data-dir-010-PtGRANAD:
    external: true
