[package]
name = "tezos_timing"
version = "1.10.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.25.1", features = ["bundled"] }
static_assertions = "1.1"
tezos_spsc = { path = "../spsc" }
tezos_conv = { path = "../conv" }
# tinyvec = { version = "1", features = ["alloc"] }
