[package]
name = "tezos_timing"
version = "v1.8.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"

[dependencies]
crypto = { path = "../../crypto" }
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.7.2"
rusqlite = { version = "0.25.1", features = ["bundled"] }
