[package]
name = "protocol-runner"
version = "0.9.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
ctrlc = "3.1.3"
failure = "0.1"
failure_derive = "0.1"
slog = "2.5"
slog-async = "2.5"
slog-term = "2.6"
# local dependencies
crypto = { path = "../crypto" }
tezos_api = { path = "../tezos/api" }
tezos_client = { path = "../tezos/client" }
tezos_context = { path = "../tezos/context" }
tezos_interop = { path = "../tezos/interop" }
tezos_interop_callback = { path = "../tezos/interop_callback" }
tezos_wrapper = { path = "../tezos/wrapper" }
