[package]
name = "protocol_runner"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
ctrlc = "3.1.3"
failure = "0.1.5"
failure_derive = "0.1.5"
slog = "2.5"
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"
# local dependencies
tezos_api = { path = "../tezos/api" }
tezos_client = { path = "../tezos/client" }
tezos_interop = { path = "../tezos/interop" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }
tezos_wrapper = { path = "../tezos/wrapper" }
