[package]
name = "fuzz_current_head_message"
version = "1.9.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"
publish = false

[dependencies]
honggfuzz = "0.5"
log = "0.4.8"
# Local dependencies
tezos_messages = { path = "../../tezos/messages" }