version: "3"

services:

  tezedge-sandbox-launcher:
    image: tezedge/tezedge:sandbox-v2.3.2
    command: ["--sandbox-rpc-port=3030"]
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
    ports:
      - "4927:4927"       # node WS port (required only for tezedge)
      - "9732:9732"       # node P2P port
      - "18732:18732"     # node RPC port
      - "3030:3030"       # sandbox launcher port
    networks:
      - default
    tty: true

  tezedge-explorer:
    image: tezedge/tezedge-explorer:v2.2.2
    environment:
      - SANDBOX=http://localhost:3030
      - API=[{"id":"sandbox","name":"sandbox","http":"http://localhost:18732", "monitoring":"", "debugger":"", "ws":"ws://localhost:4927", "features":["MONITORING","MEMPOOL_ACTION","STORAGE_BLOCK"]}]
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - default
    tty: true

volumes:
  tezedge-shared-data:
    external: false
