[package]
name = "shell_automaton_testing"
version = "2.4.0"
edition = "2021"
rust-version = "1.58"

[dependencies]
bytes = "1.0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
slab = { version = "0.4.3", features = ["serde"] }

shell_automaton = { path = "../" }
crypto = { path = "../../crypto" }
storage = { path = "../../storage" }
networking = { path = "../../networking" }
tezos_encoding = { path = "../../tezos/encoding" }
tezos_identity = { path = "../../tezos/identity" }
tezos_messages = { path = "../../tezos/messages" }
tezos_api = { path = "../../tezos/api" }
tezos_context_api = { path = "../../tezos/context-api" }
tezos_protocol_ipc_client = { path = "../../tezos/protocol-ipc-client" }
tezos_protocol_ipc_messages = { path = "../../tezos/protocol-ipc-messages" }
