[package]
name = "fuzz_encoding"
version = "1.18.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2021"
publish = false

[dependencies]
honggfuzz = "0.5"
log = "0.4.8"
rand = "0.7.3"
# Local dependencies
tezos_encoding = { path = "../../tezos/encoding" }