[package]
name = "fuzz_encoding"
version = "2.3.5"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"
publish = false

[dependencies]
honggfuzz = "0.5"
log = "0.4.8"
rand = "0.7.3"
# Local dependencies
tezos_encoding = { path = "../../tezos/encoding" }