[package]
name = "tezos_spsc"
version = "3.0.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2021"
rust-version = "1.58"

[target.'cfg(loom)'.dependencies]
loom = "0.5"

[dependencies]
