[package]
name = "networking"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bitvec = "0.9.0"
byteorder = "1.3.2"
bytes = "0.4.12"
chrono = "0.4.9"
derive_builder = "0.8.0"
derive-new = "0.5.8"
dns-lookup = "1.0.1"
failure = "0.1.5"
futures-preview = "0.3.0-alpha.19"
getset = { git = "https://github.com/Hoverbear/getset.git" }
hex = "0.4.0"
hyper = { git = "https://github.com/hyperium/hyper.git" }
lazy_static = "1.4.0"
num-bigint = "0.2.2"
num-traits = "0.2.8"
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
riker-patterns = "0.3.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
slog = "2.5"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
tokio-timer = "0.2.0-alpha.6"
# local dependencies
tezos_encoding = { path = "../tezos/encoding" }
crypto = { path = "../crypto" }
