[package]
name = "networking"
version = "0.9.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
failure = "0.1"
futures = "0.3"
hex = "0.4"
riker = "0.4"
slog = "2.5"
tokio = { version = "0.2", features = ["io-util", "time", "tcp", "rt-core"] }
# local dependencies
tezos_encoding = { path = "../tezos/encoding" }
tezos_identity = { path = "../tezos/identity" }
tezos_messages = { path = "../tezos/messages" }
crypto = { path = "../crypto" }
