[package]
name = "tezos_conv"
version = "2.4.0"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
ocaml-interop = { version = "0.8.4", features = ["without-ocamlopt", "caml-state"] }
num-bigint = "0.3"
# local dependencies
tezos_api = { path = "../api" }
tezos_context_api = { path = "../context-api" }
tezos_messages = { path = "../messages" }
tezos_protocol_ipc_messages = { path = "../protocol-ipc-messages" }
crypto = { path = "../../crypto" }
tezos-sys = { path = "../sys" }
