[package]
name = "tezos_new_context"
version = "1.4.0"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
blake2 = "0.9"
bytes = "1.0.1"
commitlog = "0.1"
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
im = { version = "15.0.0", features = ["serde"] }
lazy_static = "1.4"
leb128 = "0.2"
ocaml-interop = { version = "0.8.0", features = ["without-ocamlopt"] }
ocaml-sys = { version = "0.20.1", features = ["without-ocamlopt"] }
serde = { version = "1.0", features = ["derive"] }
sled = "0.34.6"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
snap = "1.0.4"
strum = "0.20"
strum_macros = "0.20"
# Internal dependencies
tezos-sys = { path = "../sys" }
tezos_api = { path = "../api" }
crypto = { path = "../../crypto" }

# Context actions replayer binary and his dependencies
clap = "2.33"
slog-term = "2.6"
slog-async = "2.6"

[dev-dependencies]
flate2 = "1.0"
serde_json = "1.0"
storage = { path = "../../storage" }
tezos_messages = { path = "../messages" }

[[bin]]
name = "context-actions-replayer-new"
path = "bin/context_action_file_replayer.rs"