[package]
name = "db-checker"
version = "3.1.1"
authors = ["Mambisi <mambisi.zempare@simplestaking.com> <lilbizi96@gmail.com>"]
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
edgekv = {path = "../../edgekv"}