[package]
name = "light-node"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"
default-run = "light-node"

[dependencies]
clap = "2.33.0"
dirs = "1.0.4"
failure = "0.1.5"
futures-preview = "0.3.0-alpha.18"
hex = "0.3.2"
lazy_static = "1.3.0"
log = "0.4.8"
riker = { git = "https://github.com/riker-rs/riker" }
rocksdb = "0.12.3"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
tokio = { version = "0.2.0-alpha.4", features = ["signal"] }
# Local dependencies
tezos_encoding = { path = "../tezos_encoding" }
tezos_client = { path = "../tezos_client" }
crypto = { path = "../crypto" }
networking = { path = "../networking" }
storage = { path = "../storage" }
shell = { path = "../shell" }
monitoring = { path = "../monitoring" }