[package]
name = "light-node"
version = "0.9.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"
default-run = "light-node"

[dependencies]
clap = "2.33"
failure = "0.1"
futures = "0.3"
riker = "0.4"
rlimit = "0.4.0"
serde_json = "1.0"
rocksdb = "0.15"
slog = { version = "2.5", features = ["max_level_trace"] }
slog-async = "2.5"
slog-json = "2.3"
slog-term = "2.6"
tokio = { version = "0.2", features = ["rt-threaded", "signal"] }
# Local dependencies
logging = { path = "../logging" }
tezos_api = { path = "../tezos/api" }
tezos_identity = { path = "../tezos/identity" }
tezos_messages = { path = "../tezos/messages" }
tezos_wrapper = { path = "../tezos/wrapper" }
networking = { path = "../networking" }
storage = { path = "../storage" }
shell = { path = "../shell" }
monitoring = { path = "../monitoring" }
rpc = { path = "../rpc" }
