[package]
name = "light-node"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"
default-run = "light-node"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
failure = "0.1"
futures = "0.3"
hex = "0.4"
lazy_static = "1.4"
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
rocksdb = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["max_level_trace"] }
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"
tokio = { version = "0.2", features = ["rt-threaded", "signal"] }
# Local dependencies
logging = { path = "../logging" }
tezos_api = { path = "../tezos/api" }
# TODO: TE-74 - remove deps
tezos_client = { path = "../tezos/client" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_wrapper = { path = "../tezos/wrapper" }
crypto = { path = "../crypto" }
networking = { path = "../networking" }
storage = { path = "../storage" }
shell = { path = "../shell" }
monitoring = { path = "../monitoring" }
rpc = { path = "../rpc" }