[package]
name = "context-tool"
version = "2.2.0"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "4.0", default-features = false }
clap = { version = "3.0", features = ["derive"] }
parking_lot = "0.12.0"
termcolor = "1.1.2"

# local dependencies
crypto = { path = "../../crypto" }
tezos_context = { path = "../context" }
