[package]
name = "context-tool"
version = "1.20.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "4.0", default-features = false }
clap = { version = "3.0", features = ["derive"] }
termcolor = "1.1.2"

# local dependencies
crypto = { path = "../../crypto" }
tezos_context = { path = "../context" }
