version: "3"

services:
  tezedge-memprof:
    image: tezedge/tezedge-memprof:v1.6.7
    privileged: true
    environment:
      - TEZEDGE_NODE_NAME=node_monitoring_tezedge-node_1
    volumes:
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/proc:/proc:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "17832:17832"

  tezedge-debugger:
    image: tezedge/tezedge-debugger:v1.6.7
    privileged: true
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "tezedge-shared-data:/tmp/volume/tezedge:ro"
      - "ocaml-shared-data:/tmp/volume/tezos:ro"
      - "./debugger-config.toml:/home/appuser/config.toml:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/tmp/report:/tmp/report:rw"
      - "debugger-data:/tmp/debugger_database"
    ports:
      - "17732:17732"      # debugger RPC port
      - "10001:10001/udp"  # debugger syslog port for tezedge node
      - "11001:11001/udp"  # debugger syslog port for tezos node

  tezedge-node:
    image: tezedge/tezedge:v2.3.5-frame-pointers-enabled
    pid: host
    network_mode: host
    environment:
      - TEZOS_CONTEXT=index-log-size=2_500_000
    command: ["--network", "${TEZOS_NETWORK-mainnet}", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--log", "terminal", "file", "--log-file", "/tmp/tezedge/tezedge.log", "--tezos-context-storage", "irmin", "--context-stats-db-path", "context-stats-db", "--peer-thresh-low", "15", "--peer-thresh-high", "30", "--record-shell-automaton-state-snapshots", "--record-shell-automaton-actions"]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
    depends_on:
      - "tezedge-memprof"

  ocaml-node:
    image: tezos/tezos:v12-release
    pid: host
    network_mode: host
    entrypoint: sh -c "sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr=[::]:18733 --net-addr=[::]:9733 --history-mode archive --network ${TEZOS_NETWORK-mainnet}"
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:11001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "ocaml-shared-data:/var/run/tezos/node"

  explorer:
    image: tezedge/tezedge-explorer:v2.2.3
    environment:
      # need a better way to provide such information
      - API=[{"id":"tezedge","type":"tezedge","name":"tezedge.${NODE_HOSTNAME_OR_IP:-localhost}","http":"http://${NODE_HOSTNAME_OR_IP:-localhost}:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://${NODE_HOSTNAME_OR_IP:-localhost}:4927"},{"name":"debugger","url":"http://${NODE_HOSTNAME_OR_IP:-localhost}:17732"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP:-localhost}:38732/resources/tezedge"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP:-localhost}:17832"},{"name":"resources/storage"},{"name":"mempool"},{"name":"storage"},{"name":"network"},{"name":"logs"},{"name":"state"}]},{"id":"octez","type":"octez","name":"octez.${NODE_HOSTNAME_OR_IP:-localhost}","http":"http://${NODE_HOSTNAME_OR_IP:-localhost}:18733","p2p_port":9733,"features":[{"name":"debugger","url":"http://${NODE_HOSTNAME_OR_IP:-localhost}:17732"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP:-localhost}:38732/resources/ocaml"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP:-localhost}:17832"},{"name":"resources/storage"},{"name":"mempool"},{"name":"network"},{"name":"logs"}]}]
    ports:
      - "80:80"

  monitoring:
    privileged: true
    network_mode: host
    image: tezedge/node-monitoring:v2.3.5
    pid: "host"
    command: ["--tezedge-nodes", "tezedge:18732:/tmp/tezedge", "--ocaml-nodes", "ocaml:18733:/var/run/tezos/node", "--debugger-path", "/tmp/debugger", "--wait-for-nodes", "--rpc-port", "38732"]
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
      - "ocaml-shared-data:/var/run/tezos/node"
      - "debugger-data:/tmp/debugger"

volumes:
  tezedge-shared-data:
    external: false
  ocaml-shared-data:
    external: false
  debugger-data:
    external: false
