[package]
name = "tezos_identity"
version = "v1.8.0"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# local dependencies
crypto = { path = "../../crypto" }

[dev-dependencies]
assert-json-diff = "2"
failure = "0.1"