[package]
name = "tezos_identity"
version = "0.7.1"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# local dependencies
crypto = { path = "../../crypto" }

[dev-dependencies]
failure = "0.1"