[package]
name = "tezos_identity"
version = "3.2.0"
authors = ["Branislav Kontur <branislav.kontur@viablesystems.io>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# local dependencies
crypto = { path = "../../crypto" }

[dev-dependencies]
assert-json-diff = "2"
thiserror = "1.0"

[features]
fuzzing = [ "crypto/fuzzing" ]