[package]
name = "fuzz_peer_response_message"
version = "2.2.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"
publish = false

[dependencies]
honggfuzz = "0.5"
log = "0.4.8"
# Local dependencies
tezos_messages = { path = "../../tezos/messages" }