[package]
name = "tezos_interop_callback"
version = "0.0.1-pre25"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
hex = "0.4"
ocaml = "0.8.1"
# local dependencies
tezos_context = { path = "../context" }
