[package]
name = "tezos_interop_callback"
version = "0.2.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ocaml = "0.9.3"
# local dependencies
tezos_context = { path = "../context" }
