[package]
name = "tezos_interop_callback"
version = "0.10.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ocaml-interop = { version = "0.5.0", features = ["without-ocamlopt"] }
# local dependencies
tezos_context = { path = "../context" }
