[package]
name = "tezos_interop_callback"
version = "0.5.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
znfe = { git = "https://github.com/simplestaking/znfe.git", tag="v0.1.10" }
# local dependencies
tezos_context = { path = "../context" }
