[package]
name = "tezos_interop_callback"
version = "1.1.3"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ocaml-interop = { version = "0.5.3", features = ["without-ocamlopt"] }
# local dependencies
tezos_context = { path = "../context" }
