[package]
name = "crypto"
version = "1.7.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
base58 = "0.1.0"
failure = "0.1"
failure_derive = "0.1"
hex = "0.4"
num-bigint = { version = "0.3", features = ["serde", "rand"] }
num-traits = "0.2.8"
rand = "0.7.3"
sodiumoxide = "=0.2.6"
serde = { version = "1.0", features = ["derive"] }
