[package]
name = "tezos_wrapper"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
getset = "0.0.9"
failure = "0.1"
failure_derive = "0.1"
ocaml = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
strum_macros = "0.16.0"
wait-timeout = "0.2.0"
# local dependencies
ipc = { path = "../../ipc" }
tezos_api = { path = "../api" }
tezos_context = { path = "../context" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
libc = "0.2.65"
ipmpsc = "0.2.0"
