[package]
name = "tezos_messages"
version = "1.8.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
num-bigint = "0.3"
num-traits = "0.2.8"
nom = "6.1"
anyhow = "1.0"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tezos_encoding_derive = { path = "../encoding-derive" }
quickcheck = "1.0.3"
quickcheck_derive = { git = "https://github.com/tezedge/quickcheck_derive" }
rand = "0.7.3"

[[bench]]
name = "message_benchmark"
harness = false

[[bench]]
name = "encoders_benchmark"
harness = false

[[bench]]
name = "decoders_benchmark"
harness = false

[dev-dependencies]
assert-json-diff = "2"
criterion = { version = "0.3", features = ["html_reports"]}
csv = "1.1"
serde_json = "1.0"
tezos_identity = { path = "../identity" }
