[package]
name = "tezos_messages"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
chrono = { version = "0.4.9", features = ["serde"] }
derive_builder = "0.9"
failure = "0.1"
getset = "0.0.9"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.2.2"
num-traits = "0.2.8"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }

[dev-dependencies]
assert-json-diff = "1.0.0"
