[package]
name = "tezos_messages"
version = "0.9.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.3"
num-traits = "0.2.8"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }

[[bench]]
name = "message_benchmark"
harness = false

[dev-dependencies]
assert-json-diff = "1.0.0"
criterion = "0.3"
csv = "1.1"
serde_json = "1.0"
tezos_identity = { path = "../identity" }