[package]
name = "tezos_messages"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
derive_builder = "0.8.0"
failure = "0.1.5"
getset = "0.0.9"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
# local dependencies
tezos_encoding = { path = "../encoding" }
crypto = { path = "../../crypto" }
