[package]
name = "tezos_messages"
version = "1.2.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
num-bigint = "0.3"
num-traits = "0.2.8"
# local dependencies
crypto = { path = "../../crypto" }
tezos_encoding = { path = "../encoding" }
tokio = { version = "1.2.0", features = ["io-util"]}
pin-project-lite = "0.2.6"

[[bench]]
name = "message_benchmark"
harness = false

[dev-dependencies]
assert-json-diff = "1.1"
criterion = "0.3"
csv = "1.1"
serde_json = "1.0"
async-std = { version = "1.9.0", features = ["attributes"] }
tezos_identity = { path = "../identity" }
